export interface Divorce {
    id: string,
    lawyerOneUsername: string,
    lawyerOneFirstname: string,
    lawyerOneLastname: string,
    husbandOneUsername: string,
    husbandOneFirstname: string,
    husbandOneLastname: string,
    lawyerTwoUsername: string,
    lawyerTwoFirstname: string,
    lawyerTwoLastname: string,
    husbandTwoUsername: string,
    husbandTwoFirstname: string,
    husbandTwoLastname: string,
    notary: string,
    signedByNotary: string,
    status: string,
    marriage: string,
    divorceCreated: string,
    divorceApprovedByNotary: string,
}